// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sensorpb/v1/sensorpb.proto

package sensorpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Codes int32

const (
	Codes_CODE_UNSPECIFIED        Codes = 0
	Codes_CODE_OK                 Codes = 1
	Codes_CODE_INVALID_ARGUMENT   Codes = 2
	Codes_CODE_RESOURCE_EXHAUSTED Codes = 3
	Codes_CODE_INTERNAL           Codes = 4
)

// Enum value maps for Codes.
var (
	Codes_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_OK",
		2: "CODE_INVALID_ARGUMENT",
		3: "CODE_RESOURCE_EXHAUSTED",
		4: "CODE_INTERNAL",
	}
	Codes_value = map[string]int32{
		"CODE_UNSPECIFIED":        0,
		"CODE_OK":                 1,
		"CODE_INVALID_ARGUMENT":   2,
		"CODE_RESOURCE_EXHAUSTED": 3,
		"CODE_INTERNAL":           4,
	}
)

func (x Codes) Enum() *Codes {
	p := new(Codes)
	*p = x
	return p
}

func (x Codes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codes) Descriptor() protoreflect.EnumDescriptor {
	return file_sensorpb_v1_sensorpb_proto_enumTypes[0].Descriptor()
}

func (Codes) Type() protoreflect.EnumType {
	return &file_sensorpb_v1_sensorpb_proto_enumTypes[0]
}

func (x Codes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Codes.Descriptor instead.
func (Codes) EnumDescriptor() ([]byte, []int) {
	return file_sensorpb_v1_sensorpb_proto_rawDescGZIP(), []int{0}
}

type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorName    string                 `protobuf:"bytes,1,opt,name=sensor_name,json=sensorName,proto3" json:"sensor_name,omitempty"`
	SensorValue   int32                  `protobuf:"varint,2,opt,name=sensor_value,json=sensorValue,proto3" json:"sensor_value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CorrelationId int64                  `protobuf:"varint,4,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_sensorpb_v1_sensorpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_sensorpb_v1_sensorpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_sensorpb_v1_sensorpb_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetSensorName() string {
	if x != nil {
		return x.SensorName
	}
	return ""
}

func (x *SensorData) GetSensorValue() int32 {
	if x != nil {
		return x.SensorValue
	}
	return 0
}

func (x *SensorData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SensorData) GetCorrelationId() int64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Codes                  `protobuf:"varint,1,opt,name=code,proto3,enum=sensorpb.v1.Codes" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RetryAfter    *durationpb.Duration   `protobuf:"bytes,3,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	CorrelationId int64                  `protobuf:"varint,4,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_sensorpb_v1_sensorpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sensorpb_v1_sensorpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sensorpb_v1_sensorpb_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() Codes {
	if x != nil {
		return x.Code
	}
	return Codes_CODE_UNSPECIFIED
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *Response) GetCorrelationId() int64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

var File_sensorpb_v1_sensorpb_proto protoreflect.FileDescriptor

const file_sensorpb_v1_sensorpb_proto_rawDesc = "" +
	"\n" +
	"\x1asensorpb/v1/sensorpb.proto\x12\vsensorpb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb0\x01\n" +
	"\n" +
	"SensorData\x12\x1f\n" +
	"\vsensor_name\x18\x01 \x01(\tR\n" +
	"sensorName\x12!\n" +
	"\fsensor_value\x18\x02 \x01(\x05R\vsensorValue\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12$\n" +
	"\rcorrelationId\x18\x04 \x01(\x03R\rcorrelationId\"\xae\x01\n" +
	"\bResponse\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.sensorpb.v1.CodesR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vretry_after\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\x12$\n" +
	"\rcorrelationId\x18\x04 \x01(\x03R\rcorrelationId*u\n" +
	"\x05Codes\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCODE_OK\x10\x01\x12\x19\n" +
	"\x15CODE_INVALID_ARGUMENT\x10\x02\x12\x1b\n" +
	"\x17CODE_RESOURCE_EXHAUSTED\x10\x03\x12\x11\n" +
	"\rCODE_INTERNAL\x10\x042P\n" +
	"\rSensorService\x12?\n" +
	"\tGetStream\x12\x17.sensorpb.v1.SensorData\x1a\x15.sensorpb.v1.Response(\x010\x01B?Z=github.com/samoilenko/cossack_labs/pkg/sensorpb/v1;sensorpbv1b\x06proto3"

var (
	file_sensorpb_v1_sensorpb_proto_rawDescOnce sync.Once
	file_sensorpb_v1_sensorpb_proto_rawDescData []byte
)

func file_sensorpb_v1_sensorpb_proto_rawDescGZIP() []byte {
	file_sensorpb_v1_sensorpb_proto_rawDescOnce.Do(func() {
		file_sensorpb_v1_sensorpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensorpb_v1_sensorpb_proto_rawDesc), len(file_sensorpb_v1_sensorpb_proto_rawDesc)))
	})
	return file_sensorpb_v1_sensorpb_proto_rawDescData
}

var file_sensorpb_v1_sensorpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sensorpb_v1_sensorpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sensorpb_v1_sensorpb_proto_goTypes = []any{
	(Codes)(0),                    // 0: sensorpb.v1.Codes
	(*SensorData)(nil),            // 1: sensorpb.v1.SensorData
	(*Response)(nil),              // 2: sensorpb.v1.Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
}
var file_sensorpb_v1_sensorpb_proto_depIdxs = []int32{
	3, // 0: sensorpb.v1.SensorData.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: sensorpb.v1.Response.code:type_name -> sensorpb.v1.Codes
	4, // 2: sensorpb.v1.Response.retry_after:type_name -> google.protobuf.Duration
	1, // 3: sensorpb.v1.SensorService.GetStream:input_type -> sensorpb.v1.SensorData
	2, // 4: sensorpb.v1.SensorService.GetStream:output_type -> sensorpb.v1.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sensorpb_v1_sensorpb_proto_init() }
func file_sensorpb_v1_sensorpb_proto_init() {
	if File_sensorpb_v1_sensorpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensorpb_v1_sensorpb_proto_rawDesc), len(file_sensorpb_v1_sensorpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensorpb_v1_sensorpb_proto_goTypes,
		DependencyIndexes: file_sensorpb_v1_sensorpb_proto_depIdxs,
		EnumInfos:         file_sensorpb_v1_sensorpb_proto_enumTypes,
		MessageInfos:      file_sensorpb_v1_sensorpb_proto_msgTypes,
	}.Build()
	File_sensorpb_v1_sensorpb_proto = out.File
	file_sensorpb_v1_sensorpb_proto_goTypes = nil
	file_sensorpb_v1_sensorpb_proto_depIdxs = nil
}
